-- Rinomina i dettagli vendita prodotto e aggiunge i dettagli vendita servizio.
-- Da eseguire su Supabase SQL editor.

DO $$
BEGIN
  IF to_regclass('public."dettagliovenditaProdotti"') IS NULL
     AND to_regclass('public.dettagliovendita') IS NOT NULL THEN
    ALTER TABLE public.dettagliovendita RENAME TO "dettagliovenditaProdotti";
  END IF;
END $$;

CREATE TABLE IF NOT EXISTS public."dettagliovenditaProdotti" (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "idVendita" integer NOT NULL,
  "idProdotto" integer NOT NULL,
  quantita integer NOT NULL,
  "prezzoUnitario" numeric(8,2) NOT NULL
);

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'dettagliovenditaprodotti_idvendita_fkey'
      AND conrelid = 'public."dettagliovenditaProdotti"'::regclass
  ) THEN
    ALTER TABLE public."dettagliovenditaProdotti"
      ADD CONSTRAINT dettagliovenditaprodotti_idvendita_fkey
      FOREIGN KEY ("idVendita") REFERENCES public.vendite ("idVendita") ON DELETE CASCADE;
  END IF;

  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'dettagliovenditaprodotti_idprodotto_fkey'
      AND conrelid = 'public."dettagliovenditaProdotti"'::regclass
  ) THEN
    ALTER TABLE public."dettagliovenditaProdotti"
      ADD CONSTRAINT dettagliovenditaprodotti_idprodotto_fkey
      FOREIGN KEY ("idProdotto") REFERENCES public.prodotti ("idProdotto");
  END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_dettagliovenditaprodotti_idvendita
  ON public."dettagliovenditaProdotti" ("idVendita");

CREATE INDEX IF NOT EXISTS idx_dettagliovenditaprodotti_idprodotto
  ON public."dettagliovenditaProdotti" ("idProdotto");

CREATE TABLE IF NOT EXISTS public."dettaglioVenditaServizi" (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "idVendita" integer NOT NULL,
  "idServizio" integer NOT NULL,
  "prezzoUnitario" numeric(8,2) NOT NULL
);

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'dettagliovenditaservizi_idvendita_fkey'
      AND conrelid = 'public."dettaglioVenditaServizi"'::regclass
  ) THEN
    ALTER TABLE public."dettaglioVenditaServizi"
      ADD CONSTRAINT dettagliovenditaservizi_idvendita_fkey
      FOREIGN KEY ("idVendita") REFERENCES public.vendite ("idVendita") ON DELETE CASCADE;
  END IF;

  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'dettagliovenditaservizi_idservizio_fkey'
      AND conrelid = 'public."dettaglioVenditaServizi"'::regclass
  ) THEN
    ALTER TABLE public."dettaglioVenditaServizi"
      ADD CONSTRAINT dettagliovenditaservizi_idservizio_fkey
      FOREIGN KEY ("idServizio") REFERENCES public.servizi ("idServizio");
  END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_dettagliovenditaservizi_idvendita
  ON public."dettaglioVenditaServizi" ("idVendita");

CREATE INDEX IF NOT EXISTS idx_dettagliovenditaservizi_idservizio
  ON public."dettaglioVenditaServizi" ("idServizio");
